-- =============================================================================
-- By the C — Migration 0033 · PUBLIC WEBSITE support for listings
-- =============================================================================
-- Enables the public marketing site (website/) to read listings the portal
-- writes, and to split rentals into the site's three tabs.
--
-- SAFE / ADDITIVE: adds nullable columns, a slug trigger, a public READ policy
-- (rows already meant to be public — active, non-archived listings), and a
-- website_leads intake table. Does NOT touch finances, storage buckets, or any
-- sensitive data. Apply only with Andrea's OK, as part of go-live.
--
-- NOTE ON PHOTOS: this migration does NOT expose the `documents` bucket (it holds
-- invoices + rental-application IDs — PII). The site uses listings.cover_photo_url,
-- which must resolve to a PUBLIC storage URL. Wiring a multi-photo gallery to a
-- public bucket is a separate, security-reviewed step (route to /bruno).
-- =============================================================================

-- 1) Columns -----------------------------------------------------------------
-- category: drives the website tab (for_sale / year_round_rental /
-- vacation_rental / off_season_rental). Reuses the existing property_type enum.
alter table listings add column if not exists category property_type;
comment on column listings.category is
  'Website tab category. for_sale=For Sale tab; year_round_rental=Long-term tab; vacation_rental/off_season_rental=Vacation & Winter tab. If null, the site falls back to listing_type + heuristics. The portal listing form should set this.';

-- sqft: square footage (was shown on the old Bubble site; not in original schema).
alter table listings add column if not exists sqft integer;
comment on column listings.sqft is 'Interior square footage, shown on the public site. Optional.';

-- slug: stable, human + URL friendly identifier for the public detail page.
alter table listings add column if not exists slug text;
comment on column listings.slug is 'Stable public URL slug (/listings/[slug]). Auto-generated by trigger; never recomputed once set (changing it would break indexed links).';

-- 2) Slug auto-generation (stable) -------------------------------------------
create or replace function set_listing_slug() returns trigger as $$
begin
  if new.slug is null or new.slug = '' then
    new.slug := left(
      trim(both '-' from regexp_replace(lower(coalesce(new.address, 'listing')), '[^a-z0-9]+', '-', 'g'))
      || '-' || left(replace(new.id::text, '-', ''), 8),
      80
    );
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_listing_slug on listings;
create trigger trg_listing_slug
  before insert or update on listings
  for each row execute function set_listing_slug();

-- Backfill existing rows.
update listings
   set slug = left(
     trim(both '-' from regexp_replace(lower(coalesce(address, 'listing')), '[^a-z0-9]+', '-', 'g'))
     || '-' || left(replace(id::text, '-', ''), 8),
     80
   )
 where slug is null;

create unique index if not exists idx_listings_slug on listings (slug);

-- 3) Public READ policy (anon key = the website) -----------------------------
-- Only active, non-archived listings. Additive to existing staff/realtor
-- policies (SELECT policies are OR'd).
drop policy if exists listings_public_read on listings;
create policy listings_public_read on listings
  for select
  to anon, authenticated
  using (active = true and archived_at is null);

grant select on listings to anon, authenticated;

-- 4) website_leads — public lead intake from the site's forms -----------------
create table if not exists website_leads (
  id                uuid primary key default gen_random_uuid(),
  name              text not null,
  email             text not null,
  phone             text,
  message           text,
  property_address  text,
  kind              text not null default 'contact',   -- contact | sell | listing
  source            text,                              -- which page/form
  listing_slug      text,                              -- if from a listing inquiry
  handled           boolean not null default false,
  created_at        timestamptz not null default now()
);
comment on table website_leads is 'Leads submitted from the public website forms. Anyone (anon) can INSERT; only staff (operations.edit) can read.';

alter table website_leads enable row level security;

drop policy if exists website_leads_insert on website_leads;
create policy website_leads_insert on website_leads
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists website_leads_read on website_leads;
create policy website_leads_read on website_leads
  for select
  using (has_cap('operations.edit'));

drop policy if exists website_leads_update on website_leads;
create policy website_leads_update on website_leads
  for update
  using (has_cap('operations.edit'))
  with check (has_cap('operations.edit'));

grant insert on website_leads to anon, authenticated;
grant select, update on website_leads to authenticated;

create index if not exists idx_website_leads_created on website_leads (created_at desc);
create index if not exists idx_website_leads_handled on website_leads (handled);
